### ISSUE TITLE
best model的选择

### ISSUE THREAD

**Issue by stevenDW** [GeneZC/ASGCN#1]
您好，在这份代码里，在训练过程选择模型的时候，好像没有用到验证集，而是直接每训练一次就在测试集上跑性能，根据测试集上的性能来决定模型什么时候停止训练，想问一下这样的方式是合理的吗，谢谢~

**Comment by GeneZC** [comment]
没有使用验证集的原因是：
  1. 使用的数据集没有标准的分割
  2. 之前在这个领域的研究都没有使用验证集
  3. 如果要自行分割则需要重新复现之前的所有工作

其次，我觉得不使用验证集是不合理的，建议在以后的研究中还是使用验证集，或者使用多折验证。

**Comment by peaceminumi** [comment]
您好，我按照您的步骤跑了源代码，但是结果并没有达到论文里的标准。我使用的是您提供的这个命令python train.py --model_name asgcn --dataset rest14 --save True，在执行之前，下载了glove的数据集，其他的构造图我看您已经完成了，所以直接执行了这个命令，请问还有什么需要改的吗？如果您方便的话，希望可以回复一下，谢谢

**Comment by HuG-Cloud** [comment]
你好，请问这个训练什么时候停止呢

**Comment by GeneZC** [comment]
@HuG-Cloud 模型在测试集上的F1连续5个epoch（可自行设定，见train.py）不上升就会停止

**Comment by HuG-Cloud** [comment]
谢谢，还有就是想问infer中的输出是什么呢

**Comment by GeneZC** [comment]
@HuG-Cloud 情感倾向的预测值
