### ISSUE TITLE
关于损失函数的问题

### ISSUE THREAD

**Issue by Summer-1994** [GeneZC/ASGCN#10]
请问您论文中的损失函数的c是数据集C中的每一个评论数据吗？p(hat)是每个c的实际标签？Pp(hat) 代表第p(hat)个对应的概率？也有可能是我翻译不准确的问题。其中您代码中用的是criterion = nn.CrossEntropyLoss()，这俩公式我没有搞清楚是不是一样的。

**Comment by GeneZC** [comment]
你的翻译没有问题。这两个公式是一样的，这也是交叉熵的定义。

**Comment by Summer-1994** [comment]
好滴好滴太感谢辣~
