### ISSUE TITLE
我在LAP14数据集上用ASCNN模型得出的结果远高于您在论文中给出的结果。

### ISSUE THREAD

**Issue by XGT-DLUT** [GeneZC/ASGCN#11]
您好，我在复现您的实验时，实验结果几乎没有差距。但是在LAP14上，我在ASCNN模型上得出的结果远高于您在论文中给出的结果（论文中：Acc=72.62，F1=66.72。我的结果：Acc=75.13，F1=70.73）。实验的超参我没有修改，使用的是train.py中默认的数值。您认为出现这种结果的原因是什么。

**Comment by GeneZC** [comment]
首先，实验结果的不同可能是机器的不同的导致的；
其次，现在回过头来看这个工作，有一些不太合理的地方，比如直接用测试集来选模型（而在2019年之前，这个领域的所有文章都用测试集来选模型）；
最后，ASCNN其实是我另一个工作PWCN的变种（参考：https://github.com/GeneZC/PWCN ），我一直都觉得PWCN比ASGCN来得更鲁棒，不过我在做ASGCN实验的时候的确PWCN不如ASGCN，不过既然你能跑出这么好的结果，那想必是有原因的，至于是什么原因我觉得是很值得探索的。
希望大家可以从我的工作里面学到东西，我感觉能颠覆我文中的结果是一个好开始 ：）

**Comment by XGT-DLUT** [comment]
感谢您的回复。您提到19年之前的文章都用测试集来选模型的方法不合理，那么现在较为合理的评判方法有哪些呢。（麻烦您了，初学者问题比较多😂）

**Comment by GeneZC** [comment]
从训练集中预先留一部分数据当作验证集，用在验证集上表现最好的模型在测试集上做测试。

**Comment by XGT-DLUT** [comment]
好的，谢谢 ：）

**Comment by GeneZC** [comment]
@1309059267  我最近想到另外一个可能性，就是你没有多跑几次取平均值？

**Comment by XGT-DLUT** [comment]
我印象当中是三次取均值，跑过许多次。稍等我在跑一遍。

**Comment by XGT-DLUT** [comment]
三次取均值（lap14）
max_test_acc_avg: 0.7513061650992686
max_test_f1_avg: 0.7073348764583661
超参是train.py里默认的。
我当时想的是会不会是这个数据集上的数据比较口语化，或者语法信息不明显，反而导致ascnn能达到接近asgcn的效果。我看了看数据集，水平有限实在做不出评判来。

**Comment by GeneZC** [comment]
好吧，我也不知道了。这个领域看来还需要很大的纠正😂
