### ISSUE TITLE
迭代三次模型，指标一次不如一次？

### ISSUE THREAD

**Issue by yangbaiyu** [GeneZC/ASGCN#13]
repeat: 1
max_test_acc: 0.887987012987013, max_test_f1: 0.7024944579664142
repeat: 2
max_test_acc: 0.887987012987013, max_test_f1: 0.6555064644327216
repeat: 3
max_test_acc: 0.8814935064935064, max_test_f1: 0.5690872648781992
max_test_acc_avg: 0.8858225108225107, max_test_f1_avg: 0.642362729092445
指标一次不如一次，请问最可能的原因是什么呢？

**Comment by GeneZC** [comment]
有几个进一步的问题：
1）在哪个数据上？
2）acc是差不多的？

**Comment by yangbaiyu** [comment]
上面的结果是在rest16上训练的，acc是差不多的。我将模型训练在其它数据集上也呈现f1值降低，acc变化不大的情况。

rest14结果：
repeat: 1
max_test_acc: 0.8125, max_test_f1: 0.7329873369116364
repeat: 2
max_test_acc: 0.8089285714285714, max_test_f1: 0.7177749646545495
repeat: 3
max_test_acc: 0.8089285714285714, max_test_f1: 0.7166760114398084
max_test_acc_avg: 0.8101190476190476, max_test_f1_avg: 0.7224794376686647

rest15结果：
repeat: 1
max_test_acc: 0.7896678966789668, max_test_f1: 0.6097532548752062
repeat: 2
max_test_acc: 0.7970479704797048, max_test_f1: 0.5353754492763009
repeat: 3
max_test_acc: 0.7896678966789668, max_test_f1: 0.6160886338321617
max_test_acc_avg: 0.7921279212792127, max_test_f1_avg: 0.5870724459945563

lap14结果
repeat: 1
max_test_acc: 0.768025078369906, max_test_f1: 0.7318474811574273
repeat: 2
max_test_acc: 0.7554858934169278, max_test_f1: 0.7135401017642788
repeat: 3
max_test_acc: 0.5344827586206896, max_test_f1: 0.23220973782771537
max_test_acc_avg: 0.6859979101358412, max_test_f1_avg: 0.5591991069164739

twitter结果
repeat: 1
max_test_acc: 0.7355491329479769, max_test_f1: 0.7195687082216612
repeat: 2
max_test_acc: 0.7326589595375722, max_test_f1: 0.7202286492438992
repeat: 3
max_test_acc: 0.7225433526011561, max_test_f1: 0.707570588983441
max_test_acc_avg: 0.7302504816955685, max_test_f1_avg: 0.7157893154830005

第一个问题：我在想是不是迭代模型的时候，重置参数_reset_params的问题导致模型在后续迭代过程中得到的结果不好呢？

第二个问题：
loss: 0.9353, acc: 0.6875, test_acc: 0.7614, test_f1: 0.2882
loss: 1.0296, acc: 0.6719, test_acc: 0.7614, test_f1: 0.2882
loss: 0.8005, acc: 0.7396, test_acc: 0.7614, test_f1: 0.2882
loss: 1.0177, acc: 0.7422, test_acc: 0.7614, test_f1: 0.2882
loss: 0.9575, acc: 0.7125, test_acc: 0.7614, test_f1: 0.2882
loss: 0.9731, acc: 0.7000, test_acc: 0.7614, test_f1: 0.2882
loss: 0.9333, acc: 0.6887, test_acc: 0.7614, test_f1: 0.2882
loss: 0.7607, acc: 0.7090, test_acc: 0.7614, test_f1: 0.2882
loss: 0.9911, acc: 0.7101, test_acc: 0.7614, test_f1: 0.2882
我在训练rest,lap,twitter数据集的时候，我的模型在训练前期测试集acc和f1总是不变，请问您有什么建议呢？
非常感谢！

**Comment by GeneZC** [comment]
你有调整默认的参数吗

**Comment by yangbaiyu** [comment]
没有调整的

**Comment by GeneZC** [comment]
这是我刚跑的asgcn在laptop14的结果
repeat: 1
max_test_acc: 0.7460815047021944, max_test_f1: 0.7019915292421374
repeat: 2
max_test_acc: 0.7507836990595611, max_test_f1: 0.7068784796201081
repeat: 3
max_test_acc: 0.7460815047021944, max_test_f1: 0.7045153654115061

建议检查一下embedding，因为rest14看起来很正常，而rest14我是放了embedding的。
也有可能是torch版本的问题，建议torch使用1.4及以下版本。

**Comment by yangbaiyu** [comment]
好的，非常感谢您！
我还有个问题：在rest14，rest15数据集上，训练模型1-3epoch时，训练集loss变化小，acc也变化小，测试集acc和f1值恒定不变，并且我在查看预测的标签时发现标签全部预测为正向情感，但是训练1-3个epoch之后，指标就会慢慢提升。我被这个问题困惑了一段时间，请问您您遇见过这个问题吗？如果遇见了，您怎么解决的呢？

**Comment by GeneZC** [comment]
感觉是单纯收敛慢，我觉得这并不太影响。

**Comment by yangbaiyu** [comment]
好的，感谢您的解答！
