### ISSUE TITLE
针对SemEval2014数据集的疑惑

### ISSUE THREAD

**Issue by DefuLi** [GeneZC/ASGCN#16]
请问用SemEval2014中的laptops，restaurants两个数据集，本文做的工作是SemEval2014 Task4中的subtask2吗？

就是针对Aspect term polarity的分类，而不是针对Aspect category polarity的分类？

谢谢您的解答。

**Comment by GeneZC** [comment]
是的，是针对term。

**Comment by DefuLi** [comment]
好的，谢谢大佬。
