### ISSUE TITLE
输入模型的文本长度

### ISSUE THREAD

**Issue by DefuLi** [GeneZC/ASGCN#17]
请问为什么每次输入到模型中文本的长度均不一样，是否可以通过更改代码将每次输入模型的文本长度固定

如果可以的话，请问应该修改源码中的哪部分，如果很麻烦不用太具体告知，告诉我个大概范围我自己更改就行。

谢谢大佬的解答。

**Comment by GeneZC** [comment]
需要修改bucket iterator 部分
