### ISSUE TITLE
关于源码中的.graph文件

### ISSUE THREAD

**Issue by XBJing** [GeneZC/ASGCN#18]
你好，论文中提到了两个模型ASGCN-DG和ASGCN-DT，它们的不同在于拥有不同的邻接矩阵，dependency_graph.py应该是用于生成并存储邻接矩阵的，同时源码当中也提供了得到的邻接矩阵文件，laptop_test.raw.graph等，我想知道它们对应了ASGCN-DG还是ASGCN-DT。

**Comment by GeneZC** [comment]
ASGCN-DG的
