### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by WhatTong** [GeneZC/ASGCN#19]
想问一下这个问题大概可能是什么版本出错了呀？RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

**Comment by GeneZC** [comment]
fix 了吗

**Comment by WhatTong** [comment]
> fix 了吗

可以换torch版本试试看
