### ISSUE TITLE
数据集中可能有一些错误

### ISSUE THREAD

**Issue by yangheng95** [GeneZC/ASGCN#20]
感谢作者提供的rest15和rest16的数据集，发现数据集中存在一些错误。很多句子中会出现$ t$这个符号，发生在句子中存在多个aspect的情况，我想可能是数据集处理代码的问题。我在本地进行了修改，但不确定是否引入了其他错误。大佬有时间的话可以看看

**Comment by GeneZC** [comment]
能指出一下具体位置吗

**Comment by yangheng95** [comment]
https://github.com/GeneZC/ASGCN/blob/02783d78899ac106d125dd1e3d7fd4c4ae069c59/datasets/semeval16/restaurant_train.raw#L241
在rest16和15中可以搜索到很多"$ t$"

**Comment by GeneZC** [comment]
估计是aspect重复引起的错误，看起来还挺影响evaluation的。你要是有可能的话，可以pr一下。要是重新跑了一下结果也一并在这了更新一下吧，谢谢你。

**Comment by yangheng95** [comment]
行，我最近在做gcn的实验，明天pr我的实验结果和数据集
