### ISSUE TITLE
想请教作者，第一版的asgcn（2年前发布的asgcn）中.graph生成文件使用的spacy版本和en_core_web_sm版本分别是多少？

### ISSUE THREAD

**Issue by codeyyd** [GeneZC/ASGCN#22]
想请教作者，第一版的asgcn（2年前发布的asgcn）中.graph生成文件使用的spacy版本和en_core_web_sm版本分别是多少？模型版本对精度影响还是挺大的。

**Comment by GeneZC** [comment]
环境已经丢失了，不记得了。如果是要对比的，全部都是用同一版本的结果即可，而且个人觉得差距不会太大。

**Comment by codeyyd** [comment]
好的谢谢了
