### ISSUE TITLE
模型分享请求

### ISSUE THREAD

**Issue by yangheng95** [GeneZC/ASGCN#23]
您的模型是基于GloVe的极限模型中非常出众的代表，我想请问您是否有兴趣将模型移植到https://github.com/yangheng95/PyABSA/tree/release/pyabsa/tasks/glove_apc/models 中，由于目前的有些ABSA仓库维护不及时、时常报错，所以我花了点时间构建了PyABSA，这个库主要目的是解决易用性的问题。然而由于精力不够在移植模型时出了一些问题。
请问您是否愿意将您的模型移植到PyABSA？ 谢谢您，祝您生活愉快！

**Comment by GeneZC** [comment]
我觉得挺好的，可否把你的微信发到我的邮箱，我有一些进一步的想法，方便沟通？
