### ISSUE TITLE
left_indices是指哪一部分的输入呢？

### ISSUE THREAD

**Issue by cpyhhh** [GeneZC/ASGCN#26]
![image](https://user-images.githubusercontent.com/50325174/143162268-f25e6d49-0321-4951-b253-78e4584a431d.png)

**Comment by GeneZC** [comment]
aspect左边的部分

**Comment by cpyhhh** [comment]
> aspect左边的部分

作者您好，我不大明白为什么要这么输入呢？我以为只用输入前面两项就可以了。

**Comment by GeneZC** [comment]
用来计算aspect在text_indices中对应的位置。

**Comment by cpyhhh** [comment]
> 用来计算aspect在text_indices中对应的位置。

噢 这样啊 非常感谢！
