### ISSUE TITLE
图卷积神经网络中的邻接矩阵

### ISSUE THREAD

**Issue by Summer-1994** [GeneZC/ASGCN#5]
请问图卷积神经网络公式中的di+1,为什么要 度+1 呢？谢谢~

**Comment by GeneZC** [comment]
为了避免度为0的时候分母为0，虽然说这在语法树中并不常见，并且有自循环的时候也不可能发生。你可以看作是平滑项。

**Comment by Summer-1994** [comment]
啊我懂啦~谢谢啦
