### ISSUE TITLE
How to generate the dependency tree of German or Chinese

### ISSUE THREAD

**Issue by Jiaxu-Zhao** [GeneZC/ASGCN#6]
thanks for your sharing,it's really helpful,could i know how to generate the dependency tree of German or Chinese.?Because that you process the English dataset in your code.  Thanks again^_^

**Comment by GeneZC** [comment]
As you may notice, we use SpaCy toolkit to generate dependency trees. SpaCy toolkit supports diverse languages including Englilsh and German. All you need to do is changing the model we use in our code, e.g., nlp = spacy.load('en_core_web_sm') --> nlp = spacy.load('de_core_news_sm'). The model should be downloaded before used.
As for Chinese, we suggest that you use StanfordNLP toolkit instead, which has similar functions with SpaCy.

**Comment by Jiaxu-Zhao** [comment]
Thank you so much for responding so quickly,Thanks^_^


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WhereIsMyHead"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月1日(星期五) 晚上7:52
收件人:&nbsp;"GeneZC/ASGCN"<ASGCN@noreply.github.com&gt;;
抄送:&nbsp;"赵家胥"<1402072392@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [GeneZC/ASGCN] How to generate the dependency tree of German or Chinese (#6)





 
As you may notice, we use SpaCy toolkit to generate dependency trees. SpaCy toolkit supports diverse languages including Englilsh and German. All you need to do is changing the model we use in our code, e.g., nlp = spacy.load('en_core_web_sm') --&gt; nlp = spacy.load('de_core_news_sm'). The model should download before used.
 As for Chinese, we suggest that you use StanfordNLP toolkit instead, which has similar functions with SpaCy.
