### ISSUE TITLE
您好，请问论文里的那个注意力可视化的那个彩色的表（Table 4）是怎么画的呀？

### ISSUE THREAD

**Issue by Summer-1994** [GeneZC/ASGCN#7]

**Comment by GeneZC** [comment]
Regarding the visualization of attention map, please refer to this repo: 
https://github.com/jiesutd/Text-Attention-Heatmap-Visualization

**Comment by Summer-1994** [comment]
非常感谢您~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WhereIsMyHead"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月3日(星期三) 上午10:11
收件人:&nbsp;"GeneZC/ASGCN"<ASGCN@noreply.github.com&gt;;
抄送:&nbsp;"~"<858199137@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [GeneZC/ASGCN] 您好，请问论文里的那个注意力可视化的那个彩色的表（Table 4）是怎么画的呀？ (#7)





 
Regarding the visualization of attention map, please refer to this repo:
 https://github.com/jiesutd/Text-Attention-Heatmap-Visualization
