### ISSUE TITLE
When I changed the network to "ASCNN", the following error appeared when running train.py, how to solve it?

### ISSUE THREAD

**Issue by wowowowhs** [GeneZC/ASGCN#9]
When I changed the network to "ASCNN", the following error appeared when running train.py, how to solve it?

Traceback (most recent call last):
  File "C:/Users/3403/PycharmProjects/ASGCN-master/train.py", line 226, in <module>
    ins.run()
  File "C:/Users/3403/PycharmProjects/ASGCN-master/train.py", line 149, in run
    max_test_acc, max_test_f1 = self._train(criterion, optimizer)
  File "C:/Users/3403/PycharmProjects/ASGCN-master/train.py", line 74, in _train
    outputs = self.model(inputs)
  File "C:\Anaconda\Anaconda3\envs\pt\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\3403\PycharmProjects\ASGCN-master\models\ascnn.py", line 84, in forward
    x = F.relu(self.conv1(self.position_weight(text_out, aspect_double_idx, text_len, aspect_len).transpose(1, 2)))    #whs
  File "C:\Anaconda\Anaconda3\envs\pt\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Anaconda\Anaconda3\envs\pt\lib\site-packages\torch\nn\modules\conv.py", line 208, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #3 'mat1' in call to _th_addmm_

Process finished with exit code 1

**Comment by GeneZC** [comment]
1. I expect the error happens only when you run the code on a CPU.
2. If the error happens with ASCNN, then ASGCN might suffer the same error.
3. Try 'mask = torch.tensor(mask).unsqueeze(2).float().to(self.opt.device)' --> 'mask = torch.tensor(mask).unsqueeze(2).double().to(self.opt.device)'

**Comment by wowowowhs** [comment]
Thank you very much for your answer, I am indeed using the CPU to run the program. The same problem occurred when I changed the model to ASGCN. According to your third suggestion, the same problem still appears.
I am going to reinstall the gpu to try it out. Thanks again for your answer!

**Comment by GeneZC** [comment]
The error actually never happens before, I suspect it's due to the update of PyTorch version. Hope you can fix it!

**Comment by GeneZC** [comment]
Has the problem been solved? @wowowowhs

**Comment by wdimmy** [comment]
Remove asgcn.py line 47: text_len = text_len.cpu().numpy()
                                         line48: aspect_len = aspect_len.cpu().numpy().

Same to ascnn.py.

**Comment by wdimmy** [comment]
> Thank you very much for your answer, I am indeed using the CPU to run the program. The same problem occurred when I changed the model to ASGCN. According to your third suggestion, the same problem still appears.
> I am going to reinstall the gpu to try it out. Thanks again for your answer!

Remove asgcn.py line 47: text_len = text_len.cpu().numpy()
line48: aspect_len = aspect_len.cpu().numpy().

Same to ascnn.py.

**Comment by GeneZC** [comment]
I conjecture the best solution may be change 'weight = torch.tensor(weight).unsqueeze(2).to(self.opt.device)' to 'weight = torch.tensor(weight).float().unsqueeze(2).to(self.opt.device)'
